### ISSUE TITLE
Only shown in sidebar?

### ISSUE THREAD

**Issue by joq3** [bueltge/multisite-global-media#10]
Hi,

I just downloaded this plugin because it does what I want, except one thing! It does show up in the left sidebar when you click the original Add Media button inside a post. But I have another custom plugin which adds another button where you are able to select or add media. The problem is that this one does not show the left sidebar at all. Instead it shows two selections at the top, Upload files and Media library.
Looks like this:
https://i.imgur.com/u3ynMus.png

Sadly I cannot access the global media from here, which was the reason I installed this. Do you think it is possible to add another link at the top (beside the "Upload files" and "Media library")? Or is it possible to get the sidebar to be shown here too?

I know this is outside what your plugin does, but do you think it is possible to make it show up here somehow?

The code for this media button looks like this:
https://hastebin.com/giyoyejaje.php

Thank you for your amazing work, love Adminimize too!

**Comment by bueltge** [comment]
It is like #3 but more in the context of custom plugins.

**Comment by joq3** [comment]
@bueltge that's true, did not see that one. Do you think this can be added/fixed?

**Comment by bueltge** [comment]
please try the new version 0.0.5 - https://github.com/bueltge/multisite-global-media/releases/tag/0.0.5
It implement the feature to use it also on featured image #3
