### ISSUE TITLE
Tried using, but not seeing it show on my sites

### ISSUE THREAD

**Issue by mrbm** [bueltge/multisite-global-media#11]
My network set up is:

subfolder install
S3 plugin https://wordpress.org/plugins/amazon-s3-and-cloudfront/
wpmudev domain mapping

latest version of everything, tried setting the site id (that i know has media files in it), and tried putting plugin as network activated plugin and must use plugin

However the tab does not show in my other sites for global media.

is there an additional step I am missing?

Thanks!

**Comment by mrbm** [comment]
I got it working! Couple notes:
1. Only works for add media. However using a theme like divi...it is not working. Tested it on add media for background, image insertion...not working. Why?
2. The download zip on github is not including the assets directory....weird. So had to manually recreate the directory.
3. Didn't work as a must use plugin...no idea why. Did work when network activated.

**Comment by bueltge** [comment]
The plugin enhance only the default Media Modal, no support or enhancements for thirs party plugins, themes. Currently the plugin is an idea, have sure a lot of improvements, also an additional tab on each media modal, see issue #3 

It works in my context as must use plugin, also in wp-plugins, active for the hole network.

The download of an zip file is now fixed; the assets directory was on the exclude-false list.

**Comment by joq3** [comment]
@bueltge any chance we will see https://github.com/bueltge/multisite-global-media/issues/3 implemented? Would love to be able to use this plugin!

**Comment by bueltge** [comment]
I'm not enough time for development on this topic for me. However the plugin is open source and maybe we get an pull request with an addon for this topic.

**Comment by joq3** [comment]
@bueltge how do you do a pull request? I have tried searching for a solution myself on how to add a button to the top menu, but I cannot find any information at all!

**Comment by joq3** [comment]
@bueltge If I manage to create a button on the Upload screen (sadly not on the top bar), I can manage this with this function, how do I link it to Multisite Global Media?

`add_action( 'pre-plupload-upload-ui', 'wpse_20160202_pre_plupload_upload_ui' );
function wpse_20160202_pre_plupload_upload_ui()
{
    # see https://core.trac.wordpress.org/browser/tags/4.4.1/src/wp-admin/includes/media.php#L1902

    print '<button onclick="javascript:alert(\'Upload From Dropbox\');" id="db-upload-btn" class="button media-button button-primary button-large" style="margin-bottom:10px;">Upload From Dropbox</button>';
}
`

**Comment by bueltge** [comment]
#3 is now implemented, so that I will close this issue.
