### ISSUE TITLE
DIVI and WEB Featured Image and other plugins not showing the Global Media Folder

### ISSUE THREAD

**Issue by lisandi** [bueltge/multisite-global-media#113]
We installed it as Network Activated but we can't see the Global Media Fodder in DIVI (probably other Website builders too) and not in Plugins which use Media i.e. WEN Featured Image.

What needs to be changed to make it possible that they also sow up in Website Builders/Themes and in Plugins?

**Comment by bueltge** [comment]
No 3rd party support, Sorry.
