### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'MultisiteGlobalMedia\Plugin' not found in ...

### ISSUE THREAD

**Issue by freetibet000** [bueltge/multisite-global-media#115]
Hello. I faced with this issue. Could you clarify where is i wrong?
I used composer to install plugin and after installation i have  multisite-global-media.php and folder  vendor in my mu-plugins directory. When i try load wordpress i am getting error 
PHP Fatal error:  Uncaught Error: Class 'MultisiteGlobalMedia\Plugin' not found in ...

Update:
I've installed plugin with zip file and it started work. 

Thank you

**Comment by bueltge** [comment]
Hey.
The problem is solved, because you have close it?
