### ISSUE TITLE
Does not work with Options Page (ACF)

### ISSUE THREAD

**Issue by dougcastanheira** [bueltge/multisite-global-media#118]
When using an image field for an options page created with ACF, the Global Media tab does not appear.

**Comment by Flegma** [comment]
Same problem here.
Anyone has a solution? I've tried [this](https://github.com/bueltge/multisite-global-media/issues/86) but it doesnt work.

**Comment by dougcastanheira** [comment]
Exact! I've tried this same but it doesnt work.

**Comment by bueltge** [comment]
ACF supports for now in the master edition, maybe you will try again.
