### ISSUE TITLE
Media not loading at all?

### ISSUE THREAD

**Issue by joq3** [bueltge/multisite-global-media#12]
Hi,

I'm having an issue where the media won't show up. It works great when I use the admin user, and I can see the media on all sites the admin user is connected to.
But I tried a different user, and it is just loading (the spinning icon).
The button "Global Media" shows up, but the media itself doesnt.
Nothing shows up in the console.

Is there any capability the user needs for being able to view this? Maybe I deactivated it in User Role Editor?

Also this issue is my biggest concern, as I cannot use it where I would like.
https://github.com/bueltge/multisite-global-media/issues/3
Is there any chance on fixing this?

**Comment by bueltge** [comment]
The plugin don't check capabilities. It enhanced the media modal and not more in this context. 
The #3 is now implemented so that I close this issue. Feel free to reopen if a topic is open.
