### ISSUE TITLE
Media not available in frontend

### ISSUE THREAD

**Issue by maxmichels** [bueltge/multisite-global-media#125]
Hello,

i use a theme with WPBakery. In the backend i can see the global gallery and the ID of the Image (starting with 10000...). But when i load the page in the frontend i only get a placeholder with "media not available". How can i solve it?

Max

**Comment by maxmichels** [comment]
I have located the issue in this function, where then the placeholder is loaded instead of the actual image:
File: vc_templates/vc_single_image.php:

`if (empty($media) || FALSE === get_post_mime_type( $media )) {
		if ( !function_exists('vc_is_page_editable') || !vc_is_page_editable() ) {
			$media_html = '<div class="t-entry-visual-cont"><img src="https://via.placeholder.com/500x500.png?text=media+not+available&amp;w=500&amp;h=500" /></div>';
		} else {
			$media_html = '';
		}
	} else {

		if ($media_poster === 'yes') {
			$poster = get_post_meta($media, "_uncode_poster_image", true);
			if (isset($poster) && $poster !== '') {
				$block_data['poster'] = true;
			}
		}

		if (isset($div_data['data-delay']) && $div_data['data-delay'] !== '') {
			$block_data['delay'] = $animation_delay;
		}
		$media_html = uncode_create_single_block($block_data, 'single-' . $lbox_id, 'masonry', $layout, $lightbox_classes, $carousel_textual);

		if ( function_exists( 'uncode_vc_remove_markup_from_single_media' ) ) {
			$media_html = uncode_vc_remove_markup_from_single_media( $media_html );
		}
	}`

**Comment by bueltge** [comment]
That should be a problem on WP Bakery, because it works on default and maybe Bakery use a custom function to get images.
