### ISSUE TITLE
solution for Customizer-Image-Control has a trailing ' 

### ISSUE THREAD

**Issue by wasanajones** [bueltge/multisite-global-media#131]
https://github.com/bueltge/multisite-global-media/wiki/Add-theme-support-for-the-Customizer-Image-Control

has a rogue 'add_multisite_global_media_to_customizer' );`  mark at the end

(otherwise, you guys rock!)

**Comment by wasanajones** [comment]
also.... if adding as mu-plugin...  need to change the function -
 from:  '/wp-content/plugins/multisite-global-media/assets/js/global-media.js',
to:       '/wp-content/mu-plugins/multisite-global-media/assets/js/global-media.js',

**Comment by bueltge** [comment]
Fixed in the wiki page, THanks.
