### ISSUE TITLE
no global tab is shown

### ISSUE THREAD

**Issue by mknig** [bueltge/multisite-global-media#135]
Hi,
i just installed the the plugin in the mu-plugin folder wp-version 5.8.3. 

Unfortunately i could not find any global tab at any multisite-site-media-library. When i install the and activate the plugin as normal plugin an error is thrown. 

Please let me know if i am doing wrong or if the plugin dosent work with my version .

Thank you very much in advance.

Michael.

**Comment by bueltge** [comment]
Please read the README again, set also your Site ID and check the roles, capabilities of the user about the whole network.
