### ISSUE TITLE
"ACF_Value_Filter" doesn't work with flexible content. invalid url strings

### ISSUE THREAD

**Issue by jackjonesNOW** [bueltge/multisite-global-media#137]
Fix: Comment it out to get it working to use the default ACF echo get_sub_field() the url

**Comment by bueltge** [comment]
Please describe the problem in clear words, so that also users understand it, if she has no knowledge about ACF. Describe also the process to test them and/or a recommendation for a solution. THX.

**Comment by jackjonesNOW** [comment]
Sorry I think i commented on the wrong repro. I was testing out a couple at the same time. I thought it was one of yours. Deleting now
