### ISSUE TITLE
No media is loaded?

### ISSUE THREAD

**Issue by joq3** [bueltge/multisite-global-media#18]
Hi,

I am having an issue where the Global Media never displays the media when using a different site and user than the admin user.
If I am logged in to the super admin, and create a new site, I can access the Global Media from the site ID I have setup in this plugin.

But if I create a new user and a new site, which isn't super admin, I cannot access the media. When pressing the Global Media tab I get the Wordpress loading icon, and it keeps spinning forever, not displaying any media.

Is there any special user role capabilities needed for accessing the media?

Thank you!

EDIT: No errors are shown in the console.

**Comment by joq3** [comment]
@bueltge did not know how to reopen the old one: https://github.com/bueltge/multisite-global-media/issues/12
I still cannot make this work!

**Comment by joq3** [comment]
@bueltge The user role has Import enabled. But I am not sure I understand what you are saying. Do you mean that for this plugin to work the multisite admin must have access to the site which stores the media? Doesn't that defeat the purpose? I thought I could create a "sample content" site with my super admin user, and then set the site id to this one, and after this be able to use the media from this site on all the new sites and users that are created in the network?

**Comment by bueltge** [comment]
>the multisite admin must have access to the site which stores the media
Yes. The roles concept of WP need access to the site that store data. The plugin use one site for store media files and share it about the hole network. The plugin self have no authority check.

**Comment by joq3** [comment]
@bueltge I think I have misunderstood the function of this plugin. I thought it would be possible to create a site with media, and use it's ID for everyone to use who creates a new site in the network, without them having access to the site with the media.
Would it be possible to make this happen?
Or is there some way to automatically give the new site admins access to the site with the media without them having access to edit the site?

**Comment by bueltge** [comment]
No, it is not possible to male them. It is necessary that all users, that should use media from the Global Media Site have access to the this site. IF you will change this, you should get access to media site and remove them from the UI to jump inside. Also you can change the default capability and roles concept of WP for access content from a site, but this is a lot of effort.

**Comment by holzhannes** [comment]
I also misunderstood the Plugin :-( in this point.

Ok, but for me it is no problem to add the user to the site where the images are stored. Is it right that the user must have a userlevel with the capability: upload_files in the site ID of global media? Therefore the Userlevel must be Author or above or is there a special Capability to only access the global media files?

**Comment by widoz** [comment]
@holzhannes I guess you may want to follow the discussion on #54 btw, seems like the capability needed is `upload_files`.
