### ISSUE TITLE
Media-Modal needed, currently only supports Attachment Browser

### ISSUE THREAD

**Issue by Roritharr** [bueltge/multisite-global-media#2]
It would be nice if we could add the Global Directory to the Single Image, Menu-less version of media-modal

**Comment by bueltge** [comment]
maybe like the new feature from #3

**Comment by mkormendy** [comment]
This isn't fully complete. This only addresses a specific case of the menuless media modal for the featured image. Some plugins and themes use the menuless media modal, and the Global Media tab (on the top) doesn't show up.

**Comment by bueltge** [comment]
@mkormendy I think you should add a new issue with this requirements,  so that we understand the goal, the current problem. Thx!
