### ISSUE TITLE
Switch to wordpress-muplugin Composer type

### ISSUE THREAD

**Issue by johnbillion** [bueltge/multisite-global-media#23]
I think it makes sense for this plugin to be defined as a `wordpress-muplugin` in the Composer file, instead of a `wordpress-plugin`.

That way, a custom installation path doesn't need to be defined in order for this to be installed as a mu-plugin.

**Comment by bueltge** [comment]
Hi @johnbillion 
It should done, was a mistake on one of my local clients, a mistake between gitignores.
Now I have also push the tag again and it should work.

Please feel free and repopen the issue if it will not work or is still open in this context.
Thanks for your hint!
