### ISSUE TITLE
WooCommerce Gallery images

### ISSUE THREAD

**Issue by jdyach** [bueltge/multisite-global-media#27]
Are there any known issues with WooCommerce product galleries? I am using Avada theme, and am able to choose the Global Media item to insert in the product gallery, but once I Publish/Update, it disappears as if I never added it.

**Comment by bueltge** [comment]
Im personal not an expert in Woo. Do you mean this function from Woo?
https://docs.woocommerce.com/document/adding-product-images-and-galleries/

Have you knowledge wich code, function from Woo add this feature. I think our plugin can't support theme because is it an additional custom function from Woo.

**Comment by widoz** [comment]
Seems the problem is the ID of the thumbnails. 

If I try to add a thumbnail by the current site I get the id but when I try to add a thumbnail by the global media I get something like: 10000062,10000055,10000056,10000049 where the latest two digits are the id of the media post.

Then when I try to save the product i lost the values passed to it because of `$image_ids = array_filter( $image_ids, 'wp_attachment_is_image' );` within `woocommerce/includes/abstracts/abstract-wc-product.php:set_gallery_image_ids`

So the gallery isn't stored because the attachment doesn't exists in that specific site.

**Comment by GideonRoose** [comment]
Are there any plans to add this enhancement in the near future?

**Comment by widoz** [comment]
@GideonRoose We are working on a solution for cases like this one.

**Comment by bueltge** [comment]
@widoz I have tested all core features of the plugin, without WooCommerce and it works. Thanks a lot again!
@GideonRoose @EdithAllison please can you test this version?
Please [use the zip from here](https://github.com/bueltge/multisite-global-media/releases/tag/0.1.0-alpha), if you haven't knowledge about different branches and composer. Thanks a lot.

**Comment by GideonRoose** [comment]
@bueltge Works like a charm! One thing is off, which is logical and I understand if this won't be a priority functionality. It doesn't work with the **WooCommerce Additional Variation Images** plugin. See attached images.
[This is the plugin page](https://woocommerce.com/products/woocommerce-additional-variation-images/)

![image](https://user-images.githubusercontent.com/43746415/47346597-d1a8ff80-d6ad-11e8-9d21-5b8f27aa5fab.png)

![image](https://user-images.githubusercontent.com/43746415/47346771-20ef3000-d6ae-11e8-8c2c-0a7da26ddd7e.png)

**Comment by EdithAllison** [comment]
Works perfectly now with WooCommerce. Tested with product image and product gallery images, both now working as expected.  👍 
<img width="302" alt="bildschirmfoto 2018-11-01 um 10 28 42" src="https://user-images.githubusercontent.com/19706428/47843812-ff362d00-ddc0-11e8-9b13-a9bcaebe51b9.png">

Thank you very much!

**Comment by EdithAllison** [comment]
Not yet working: The thumbnail in the WooCommerce product overview in admin is empty.  The thumbnail is often used by admins to quickly skim through products, 

<img width="1244" alt="bildschirmfoto 2018-11-01 um 15 37 45" src="https://user-images.githubusercontent.com/19706428/47858388-40900200-ddec-11e8-9973-77ce7fdf6e0f.png">

responsible function is in file /woocommerce/includes/admin/list-tables/class-wc-admin-list-table-products.php on line 140  (file version 3.3.0) : 

```
	/**
	 * Render columm: thumb.
	 */
	protected function render_thumb_column() {
		echo '<a href="' . esc_url( get_edit_post_link( $this->object->get_id() ) ) . '">' . $this->object->get_image( 'thumbnail' ) . '</a>'; // WPCS: XSS ok.
	}
```

**Comment by widoz** [comment]
@EdithAllison This will be fixed in the latest version. We added support for a function in #53 and I tested that also fix the issue with the thumbnail in the edit post screen.

Waiting for a  new package @bueltge

**Comment by widoz** [comment]
@EdithAllison Please try this release regarding the thumbnails within the products overview page https://github.com/bueltge/multisite-global-media/releases/tag/0.1.0-beta

Thanks a lot

**Comment by EdithAllison** [comment]
Thank you, that works great! Thumbnails are now showing in the product overview in admin.

**Comment by EdithAllison** [comment]
Not necessarily an issue but a request for enhancement: The global media gallery does not appear for WooCommerce category thumbnails ( Products > Categories : Add Thumbnail).

**Comment by widoz** [comment]
Thanks @EdithAllison I've opened a different issue for that https://github.com/bueltge/multisite-global-media/issues/59
