### ISSUE TITLE
Feature Image Funtionality Request

### ISSUE THREAD

**Issue by vefusion** [bueltge/multisite-global-media#3]
This plugin works smoothly! If it also worked under the feature image it wold be amazing! Instead of being available through the left side-tab it would have to be available at the top next to the "Upload Files" and "Media Library" options. Please look at the screenshot. Is this possible?

![6ph7u](https://cloud.githubusercontent.com/assets/20918938/17503868/6ccb39fa-5dc1-11e6-910b-63842722563b.png)

**Comment by bueltge** [comment]
Hi and thanks for the first praise.

I think it is also possible to add this possibility to the featured image media modal. But I have't not really time for the topic. I will see, what can I do. 
Also the hint, Pull request are really welcome, maybe you or other create a enhancement.

Best.

**Comment by lopesval** [comment]
would be amazing if this functionality was present! cheers!

**Comment by carstenwawer** [comment]
I dont get how this should work. The featured image is a reference-id in the post-meta-fields. So you would have to copy the attachment over to the new site or do some pretty intense wp-hook-hacking to get this to work.

Or am i missing something?

**Comment by bueltge** [comment]
The meta data of the post should reference the image from the global media site. 
however a discussion are really welcome.

**Comment by marinamat76** [comment]
Any news about this request?
It is a pity that there is no integration of feature image.

**Comment by joq3** [comment]
Is there a chance this will be implemented?

**Comment by bueltge** [comment]
:boom: Thanks a lot to @magicworks for a pull request there implement, fixed this feature. Really great! :clap: 
Would love to see more contributions in this form. Beautiful.

**Comment by marinamat76** [comment]
Umh..for me seems to not work propertly! 
My case:
- I open correctly the "Featured Image" iframe
- I open correctly the "Global Media" tab
- I can select correctly a global picture
But when i click the button "Set featured Image" the modal closed and nothing happens (not even some javascript errors from the browser console)

Maybe something escapes me?

Thank's
Marina.

**Comment by bueltge** [comment]
@marinamat76 I open #15 for this.
