### ISSUE TITLE
Inpsyde coding standard require camelCase where code use snake case

### ISSUE THREAD

**Issue by widoz** [bueltge/multisite-global-media#34]
I guess we can disable the camelCase for phpcs in case you want to keep the snake case style.

**Comment by bueltge** [comment]
No. I would switch for longer view to camelCase, also php 7 as minimum level.

**Comment by bueltge** [comment]
Now, I hope I switched all variables and method to the right codex.

**Comment by bueltge** [comment]
This topic should be done. If we find open strings, we change it from time to time.
