### ISSUE TITLE
Do not use phpcs:disable without a phpcs:enable and the rule name

### ISSUE THREAD

**Issue by widoz** [bueltge/multisite-global-media#35]
When you use the `phpcs:disable` all of the following code will not be checked for phpcs issues, that means for the rest of the file unless you call `phpcs:enable` the code will not checked for coding standard violations.

I suggest to use `phpcs:ignore Sniff_Name` if you want to ignore a single line of code and use `phpcs:disable Sniff_Name` when you want to ignore more line of code but call `phpcs:enable` after the code you want to ignore.

Adding the sniff name allow us to know which kind of violation we want to ignore.
See https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file for more info and examples.

**Comment by bueltge** [comment]
Thanks a lot for this hint, is really new for me! Thanks also for the fix via #36

**Comment by widoz** [comment]
Going to close this since it was merged
