### ISSUE TITLE
Question about functionality

### ISSUE THREAD

**Issue by trewknowledge** [bueltge/Multisite-Global-Media#4]
Just to confirm, users must upload images into the site defined in the SITE_ID constant to be used across other sites in the network.

For example, if SITE_ID is set to 3 and I am on site ID 5 and upload an image, it won't be accessible to other sites in the network.

Is that correct?

**Comment by bueltge** [comment]
Yes. The image must be uploaded in the site, there is defined. The focus was, that a author team upload the images, thee others can use in all sites.
