### ISSUE TITLE
when running PHP 7.2 getting error when attempting to use a global media item on post featured image

### ISSUE THREAD

**Issue by mrbm** [bueltge/multisite-global-media#42]
Trying to have a global media item for a blog post as the featured image! Running subblog set up with php 7.2..everything seems great except for this, here's the error:

<b>Fatal error</b>:  Uncaught TypeError: Argument 2 passed to MultisiteGlobalMedia\adminPostThumbnailHtml() must be of the type integer, null given, called in /srv/users/serverpilot/apps/wordpress/public/wp-includes/class-wp-hook.php on line 286 and defined in /srv/users/serverpilot/apps/wordpress/public/wp-content/plugins/multisite-global-media-master/multisite-global-media.php:338
Stack trace:
#0 /srv/users/serverpilot/apps/wordpress/public/wp-includes/class-wp-hook.php(286): MultisiteGlobalMedia\adminPostThumbnailHtml('&lt;p class="hide-...', NULL, 1908)
#1 /srv/users/serverpilot/apps/wordpress/public/wp-includes/plugin.php(203): WP_Hook-&gt;apply_filters('&lt;p class="hide-...', Array)
#2 /srv/users/serverpilot/apps/wordpress/public/wp-admin/includes/post.php(1448): apply_filters('admin_post_thum...', '&lt;p class="hide-...', NULL, 1908)
#3 /srv/users/serverpilot/apps/wordpress/public/wp-content/plugins/multisite-global-media-master/multisite-global-media.php(358): _wp_post_thumbnail_html(1908, NULL)
#4 /srv/users/serverpilot/apps/wordpr in <b>/srv/users/serverpilot/apps/wordpress/public/wp-content/plugins/multisite-global-media-master/multisite-global-media.php</b> on line <b>338</b>

going to line 358 reveals:
```
    // $thumbnailId is passed instead of postId to avoid warning messages of nonexistent post object.
    $content = _wp_post_thumbnail_html($thumbnailId, $postId);
```
So perhaps 7.2 is less for giving of the use of NULL?

Suggestions for a quick patch?

**Comment by widoz** [comment]
@mrbm Could you kindly check pull request #46 ? I guess you'll find it useful to solve this issue.

**Comment by widoz** [comment]
Duplicate issue, have a look at #15 may be we could continue the discussion there.

**Comment by bueltge** [comment]
See #15
