### ISSUE TITLE
Even though item is selected does not output featured image

### ISSUE THREAD

**Issue by mrbm** [bueltge/multisite-global-media#44]
Using the divi theme and php 7.2

Not seeing featured image output in a standard listing of posts, nor seeing it in the visual builder listing of posts, nor seeing it in the actual non visual builder post.

Not seeing an error message either.

So I'm guessing its not switching to the right blog to grab the post.

**Comment by widoz** [comment]
Hi @mrbm  Could you kindly check pull request #46 may be that could solve also this issue.

**Comment by bueltge** [comment]
@mrbm please test the current master, there have also include the #46

**Comment by mrbm** [comment]
hello @widoz and @bueltge  those updates work for me, am able to see the item set in the featured image admin area of a post. 

That said, when rendering to front, i don't see the image in the visual builder style pages for blog posts nor do I see it if divi is set to non-visual builder mode and then I am viewing the index of blog posts page set in the admin area nor on the single blog page.

I'd also like to note I am testing with the amazon s3 remote image plugin.

Everything else is working great though!

**Comment by widoz** [comment]
@mrbm Did you experience in the same issue if you use a WordPress default theme?

**Comment by mrbm** [comment]
@widoz closed related to 48
