### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by scottbasgaard** [bueltge/Multisite-Global-Media#5]
Can't get it working today and will dig into it more but would love to know current status :)

**Comment by bueltge** [comment]
HI @scottbasgaard 
The plugin should work. I have currently no active installation under maintenance, there I use the plugin. But I haven't also no informations from customers there use it active in his sites.
Try it and give me feedback if you found problems, features are currently not on our timeline, leave it as issue for later work or send a pull request, it is really welcome.

**Comment by scottbasgaard** [comment]
Thanks @bueltge! After some further testing it's 👍 

Now need to take a look at #3 and see if it's possible :)
