### ISSUE TITLE
can't get the new version to work

### ISSUE THREAD

**Issue by mrbm** [bueltge/multisite-global-media#53]
getting the error:
No suitable autoloader found. Multisite Global Media cannot be loaded correctly.

Further more...it looks like the file: multisite-global-media.php has changed

The instructions in the readme don't make sense...

`const SITE_ID = 1;`

Is gone

```
add_filter( 'global_media.site_id', function() {
    return 1234;
} );`.
```
Has 
``.`
Which seems to be a typo?

Anyways would love to know how to get this going again to test. I manually put in const SITE_ID = 1; and the filter but both still give me the error.

thanks

**Comment by bueltge** [comment]
The autoload will create after composer update. If you not familar with composer please use the zip from the release page https://github.com/bueltge/multisite-global-media/releases/tag/0.1.0-alpha
And yes, define the site ID only via custom plugin and the small code include the hook. We will a solid solution without change inside the files. However we need a update of the readme to get a clean how to. Thanks for your tests.

**Comment by UnionDesign** [comment]
Sorry I'm getting "No suitable autoloader" even when I hardcode the ID to "1" or don't add any code or plugin at all (which should work because 1 is the default). Been bashing away for 2 hours. Can't get it to work. I don't use composer.

**Comment by bueltge** [comment]
Have you use the zip package from the release page, link above?

**Comment by UnionDesign** [comment]
Thanks no. I downloaded the zip from the code page. Sorry. I'll try now. I also figured out that I just have to put the plugin in the mu folder to get past the autoload error. One sec.

**Comment by UnionDesign** [comment]
Thanks! Sorry for being an idiot. The release zip doesn't throw any errors but also doesn't appear to do anything. My main blog is ID 1 (so no need to change it) but none of the subsites are seeing any media and I don't see any tabs or anything. I'll try to find another solution. The "Network Media Library" plugin looked promising but has a couple bugs.

**Comment by bueltge** [comment]
Please go to your site with ID 1, upload media files. Now go to a other site, like ID 2 and edit a post. On the edit post screen open the modal from the media library and you should see the link for the Global Media.

**Comment by mrbm** [comment]
@bueltge 

Hey there, so I network activated and got it to load.

Unfortunately there is still an issue with it not working on blog posts output with S3 plugin and Divi theme.

It shows in the admin section, it shows when using the visual builder and when inserting media non visual builder, however the thumbnail is not showing in the output when listing posts or visiting a single post.

Reviewing their "single.php" reveals they have a custom function called:

get_thumbnail()

I am wondering if this has something to do with how Divi shows blogs post thumbnail data.

here's what function get_thumbnail looks like:

```
/* this function gets thumbnail from Post Thumbnail or Custom field or First post image */
if ( ! function_exists( 'get_thumbnail' ) ) {

        function get_thumbnail($width=100, $height=100, $class='', $alttext='', $titletext='', $fullpath=false, $custom_field='', $post='') {
                if ( empty( $post ) ) global $post;
                global $shortname;

                $thumb_array['thumb'] = '';
                $thumb_array['use_timthumb'] = true;
                if ($fullpath) $thumb_array['fullpath'] = ''; //full image url for lightbox

                $new_method = true;

                if ( has_post_thumbnail( $post->ID ) ) {
                        $thumb_array['use_timthumb'] = false;

                        $et_fullpath = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), 'full' );
                        $thumb_array['fullpath'] = $et_fullpath[0];
                        $thumb_array['thumb'] = $thumb_array['fullpath'];
                }

                if ( empty( $thumb_array['thumb'] ) ) {
                        if ( empty( $custom_field ) ) $thumb_array['thumb'] = esc_attr( get_post_meta( $post->ID, 'Thumbnail', $single = true ) );
                        else {
                                $thumb_array['thumb'] = esc_attr( get_post_meta( $post->ID, $custom_field, $single = true ) );
                                if ( empty( $thumb_array['thumb'] ) ) $thumb_array['thumb'] = esc_attr( get_post_meta( $post->ID, 'Thumbnail', $single = true ) );
                        }

                        if ( '' === $thumb_array['thumb'] && et_grab_image_setting() ) {
                                $thumb_array['thumb'] = esc_attr( et_first_image() );
                                if ( $fullpath ) $thumb_array['fullpath'] = $thumb_array['thumb'];
                        }

                        #if custom field used for small pre-cropped image, open Thumbnail custom field image in lightbox
                        if ($fullpath) {
                                $thumb_array['fullpath'] = $thumb_array['thumb'];
                                if ( empty( $custom_field ) ) $thumb_array['fullpath'] = apply_filters( 'et_fullpath', et_path_reltoabs( esc_attr( $thumb_array['thumb'] ) ) );
                                elseif ( ! empty( $custom_field ) && get_post_meta( $post->ID, 'Thumbnail', $single = true ) ) $thumb_array['fullpath'] = apply_filters( 'et_fullpath', et_path_reltoabs( esc_attr( get_post_meta( $post->ID, 'Thumbnail', $single = true ) ) ) );
                        }
                }

                return $thumb_array;
        }

}
```

Any suggestions on a work around? Thanks

**Comment by mrbm** [comment]
@bueltge you around...?

**Comment by widoz** [comment]
@mrbm @bueltge I added support for `wp_get_attachment_image_src`. 
Do you want to have a package to test it or do you are able to use composer?
See pull request #56 https://github.com/bueltge/multisite-global-media/pull/56

**Comment by mrbm** [comment]
I can't use composer....would be better without composer :D

**Comment by mrbm** [comment]
@widoz 

Also thanks for working through it. I just added the code to the alpha manually

```
add_action('the_content', function () {
    $thumbId = get_post_thumbnail_id();
    $imageSrc = wp_get_attachment_image_src($thumbId);
     var_dump($imageSrc);
    exit;
}); 
```

Seems to be giving issue...why is this there?

**Comment by bueltge** [comment]
@mrbm Here is the current version for testing, usable without Composer knowledge - https://github.com/bueltge/multisite-global-media/releases/tag/0.1.0-beta

**Comment by argyrg** [comment]
As an end user this looks like just what I need. But I hit the "No suitable autoloader found. Multisite Global Media cannot be loaded correctly" issue with the released zip version so searched for and found the beta.zip version and tried that.

I'm not getting the error message but nor am I getting a 'Global' tab on any of my sites.

I've uploaded it, installed it, network activated it and confirmed that site_id=1 I then uploaded images on a couple of the sites. I've tried moving it to mu-plugins directory with the same (lack of) results. Am I missing something in the installation process?

**Comment by widoz** [comment]
@argyrg Sorry not able to reproduce the issue with the latest package https://github.com/bueltge/multisite-global-media/releases/download/0.1.0-beta/multisite-global-media-0.1.0-beta.zip please try to remove the plugin directory, clean the browser cache and try to install it again. 
If still not works please open a different issue.

**Comment by mrbm** [comment]
any updates to address this:
"No suitable autoloader found. Multisite Global Media cannot be loaded correctly."
Additionally, when using the 0.1 dev version, if using woocommerce there is a conflict with product gallery images and quick edit.

if your plugin is active it will remove the product image gallery on a woocommerce product when performing any action on quick edit...as I found out the hard way with 21 products each having 12 images....

Not sure why...but after activating and deactiving every plugin on my network...multisite global media plugin was the issue. So I am trying to update to latest version...but still getting the:
"No suitable autoloader found. Multisite Global Media cannot be loaded correctly."
message...ideas?

**Comment by bueltge** [comment]
You have still tested the last releases 0.1.0-beta - https://github.com/bueltge/multisite-global-media/releases/download/0.1.0-beta/multisite-global-media-0.1.0-beta.zip ?

@widoz Maybe you will look at the comment from @mrbm

**Comment by widoz** [comment]
@mrbm @bueltge I answered in #81  already
