### ISSUE TITLE
readme Update

### ISSUE THREAD

**Issue by bueltge** [bueltge/multisite-global-media#58]
We need a readme update.

The option to set the site ID inside the file is not longer necessary! Only the way about the hook is the right way. Maybe we need more explanatory notes for users there have no knowledge for custom plugins.

Also we need several fixes in the English grammar context.

**Comment by EdithAllison** [comment]
I'm happy to help with this. I'm new to github, a readme would be a useful first task, and I can explain how to set up a custom plugin. PS I'm a native German speaker but am confident in English.

**Comment by bueltge** [comment]
Hi @EdithAllison 
that would be fine! I will wait for your Pull Request on this topic.

**Comment by bueltge** [comment]
Fixed with #61
