### ISSUE TITLE
No suitable autoloader found. Multisite Global Media cannot be loaded correctly.

### ISSUE THREAD

**Issue by holzhannes** [bueltge/multisite-global-media#62]
With the new Version I have this Issue: 
![bildschirmfoto 2018-11-08 um 20 04 33](https://user-images.githubusercontent.com/4320619/48221811-f0d0ae00-e38a-11e8-9040-29c0a349e94d.png)

**Comment by holzhannes** [comment]
I still see the autoloader error even if I use https://github.com/bueltge/multisite-global-media/releases/download/0.1.0-beta/multisite-global-media-0.1.0-beta.zip.

**Comment by widoz** [comment]
@holzhannes That's really wired, I just tried it and have no problems.
Try to deactivate all plugins and clean the browser cache and let us know.

**Comment by widoz** [comment]
@holzhannes  Please try the following package https://github.com/bueltge/multisite-global-media/releases/download/0.1.0-beta/multisite-global-media-0.1.0-beta.zip this have the autoloader in there.

**Comment by holzhannes** [comment]
@widoz It tested today, now it is working, sorry for my late response!
Just one Question. Inside the folder vendor are a lot of files (1806) are they all needed to run the plugin or is this just due to beta version?

**Comment by raminramesh** [comment]
is there new version of multisite global media beta with the loader? 

because I see the version 0.1.1 of this plugin without loader

**Comment by mariohamann** [comment]
> is there new version of multisite global media beta with the loader?
> 
> because I see the version 0.1.1 of this plugin without loader

Need this one too.

**Comment by mariohamann** [comment]
> is there new version of multisite global media beta with the loader?
> 
> because I see the version 0.1.1 of this plugin without loader

You have to download the "tagged" versions, not the repo. 
https://github.com/bueltge/multisite-global-media/releases/tag/0.1.1

**Comment by bonysoft** [comment]
there is no "composer/autoloader free" package for 0.2.0 release, please add
