### ISSUE TITLE
Global Media tab is not displayed if pushing the "Add Media" button.

### ISSUE THREAD

**Issue by holzhannes** [bueltge/multisite-global-media#63]
I am using version 0.0.8 because of https://github.com/bueltge/multisite-global-media/issues/62#issuecomment-437227693, therefore i am not sure what is the behaviour in the https://github.com/bueltge/multisite-global-media/releases/tag/0.1.0-beta version.

If I push the Add Media button above the WordPress editor I will see this view where it is only possible to add media from the left menu and not via Tab. Would be great to see the tab here as well.

![push-add-media](https://user-images.githubusercontent.com/4320619/48258998-82353400-e40e-11e8-9c3a-23b3ebf7c311.png)

**Comment by widoz** [comment]
I don't know, that depends on the media modal, the first one "Add Media" is a view that contains two tabs, where the "Global Media" is a different view.

**Comment by bueltge** [comment]
Also in the context of Gutenberg we should valifate them, is it really necessary. The default media modal have not enough possibilities to add the tab, only a hack would add this, but is hard to maintain. The media library is usable so I think we should close this issue and concentrate to the other open issues. If I'm wrong, please open again and add your view, reasons. Thx.
