### ISSUE TITLE
any updates on the "no suitable autoloader" bug with the master

### ISSUE THREAD

**Issue by mrbm** [bueltge/multisite-global-media#64]
Hey guys, I know I could do an older alpha version, but I see the master has more recent updates an fixes and would love to get on track with the latest and greatest...is there a "no suitable autoloader" bug fix in the pipeline?

Thanks!

**Comment by bueltge** [comment]
You find usable packages in the release page - https://github.com/bueltge/multisite-global-media/releases
The last 0.1.0-beta is include a autoloader, no knowledge in Composer necessary.
Please use the attached zip - https://github.com/bueltge/multisite-global-media/releases/download/0.1.0-beta/multisite-global-media-0.1.0-beta.zip
