### ISSUE TITLE
Intalling latest beta through composer is broken

### ISSUE THREAD

**Issue by killua99** [bueltge/multisite-global-media#67]
Latest beta is broken since is reading a folder that does not exists.

If you manage your project with composer is logic that the vendor folder wont be at the same level as the mu plugin, so the autoloader "detector" thing it has nothing and fails the bootstrap.

**Comment by bueltge** [comment]
The current version is only a dev version so that I not change the version number of the plugin. But thanks a gain for your help! :heart:

**Comment by killua99** [comment]
Sure, but, is a -beta flag at least should build right.

There is any plan roadmap to read to push further this plugin? I'm quite interesting on improve more this plugin.

Also what kind of feature can I submit in here?

**Comment by bueltge** [comment]
We have topics inside the issue list, so that you can help on each ticket to solve them. It would be really nice!
