### ISSUE TITLE
Introduce IIFE within the main plugin file to not expose functions

### ISSUE THREAD

**Issue by widoz** [bueltge/multisite-global-media#69]
Within the main plugin file we are using a namespace to prevent conflicts with other plugins but that doesn't prevent third party code to access and use functions and variables needed only to bootstrap the plugin. 

I would suggest to introduce an IIFE that will wrap the entire main plugin file code to bootstrap the plugin, functions included like so:

```php
(function() {
    // Bootstrap code
})();
```

**Comment by bueltge** [comment]
@widoz The issue should done. Is my change correct for your opinion? Maybe you can close the issue.

**Comment by bueltge** [comment]
We should more discuss that topic in a call, makes more easier to understand and look an the topics. I'm not sure why we should create a third party library. But yes, reusable is a topic and espically inside the bootstrap and the mocking functions of tests we have potentially to create code there we can use in other solutions.

**Comment by widoz** [comment]
I was meant in case we want to have reusable functions for different other plugins, could be useful to pack those functions: `adminNotice`, `autoload` etc... within the same package and require that package in mgm, so we can reuse them and don't need to worry about exposing unnecessary functionalities during bootstrap.
