### ISSUE TITLE
Can't use plugin with composer

### ISSUE THREAD

**Issue by gnowland** [bueltge/multisite-global-media#7]
See PR #8
EDIT: You'll also will need to add a "release" for this to work with composer!

**Comment by gnowland** [comment]
although on install I see that you have a CONST defined for the site.... maybe make that into a hook so it can be redefined in the theme (`functions.php`) without being destroyed on next composer update?

**Comment by bueltge** [comment]
Hi @gnowland 
thanks for your idea, request! I have changed the source a little bid, so that we have an WordPress way to change the id via Hook. Also I cleanup the code, the json and release an new version, also now live on packagist.org.
This shoulds helps you, or?

**Comment by gnowland** [comment]
That's perfect, thanks!! Thanks for the quick reply!

**Comment by bueltge** [comment]
:100:
