### ISSUE TITLE
Enqueue Assets, do not use version but filemtime to ensure the file is cached but updated when his content change

### ISSUE THREAD

**Issue by widoz** [bueltge/multisite-global-media#71]
When we register the assets (js/css) actually we are using a version number that will help us on cache the assets but this could lead of problems in case the file change because of a new release.
If the file change we should update the version of the file all of the time. 

Instead what about using `filemtime` that generate a version for the asset but change when the file change, so it get cached but updated when necessary allowing us to forgot to do this unnecessary step.

So instead of 

```php
wp_register_script(
    'global_media',
    $this->pluginProperties->dirUrl() . '/assets/js/global-media.js',
    ['media-views'],
    '0.1',
    true
);
```

it could be

```php
wp_register_script(
    'global_media',
    $this->pluginProperties->dirUrl() . '/assets/js/global-media.js',
    ['media-views'],
    filemtime($this->pluginProperties->dirPath() . '/assets/js/global-media.js'),
    true
);
```

**Comment by bueltge** [comment]
Sure, filemtime is a simple solid solution. Thanks for the hint.

**Comment by bueltge** [comment]
@widoz The issue should done. Is my change correct for your opinion? Maybe you can close the issue.
