### ISSUE TITLE
Error After Install: No Suitable Autoloader Found

### ISSUE THREAD

**Issue by Xarcell** [bueltge/multisite-global-media#75]
I get the alert message: No suitable autoloader found. Multisite Global Media cannot be loaded correctly.

This was install on a multisite network, where the default ID is used.

**Comment by bueltge** [comment]
Do you use the master branch version? Have you install composer? That's necessary for the plugin. If you haven't knowledge about Composer please use the zip download on the release page.

**Comment by Xarcell** [comment]
I did not install composer. I have no interest in installing composer, but thanks.

**Comment by bueltge** [comment]
OK, so I close the issue.

**Comment by mrbm** [comment]
are you guys moving forward with requiring composer...if so why.

**Comment by Xarcell** [comment]
There already is a version thst doesn't require composer and is actively developed: https://github.com/humanmade/network-media-library

**Comment by bueltge** [comment]
@Xarcell This version is more different from this plugin, that's the point that we no get a PR inside the plugin. 

@mrbm Composer is really helpful to manage the dependency topic, is really typical for modern php development. You should find a lot of posts about it. You find always a zip package in the release page to easy install, like WordPress process. https://github.com/bueltge/multisite-global-media/releases

**Comment by trivendor** [comment]
works great, thank you
releases version multisite-global-media-0.1.0-beta.zip
must use loader
Multisite Global Media Site ID

Network Media Library would work on a new multisite, but one with existing subsites that have media it is not suitable (from what I tested)

**Comment by klogges** [comment]
I have the same error on version 0.2.0.
Tried to install via composer and via latest release zip (with must use loader plugin).

**Comment by alevals** [comment]
same here. I'm having the same error with version 0.2.0
