### ISSUE TITLE
Having a difficult time installing

### ISSUE THREAD

**Issue by peter-mumford** [bueltge/multisite-global-media#76]
I'm trying to wade through the installation process.

1. I used composer to install the plugin, and it installed both Multisite Global Media AND Network Global Media into mu-plugins. That didn't seem right. And I got errors.
2. I deleted those plugins, and downloaded the zip for this plugin into my mu-plugins folder. I ran composer install inside the plugin.. but it won't run:  There is no package.json.  
3. I find a package.json on your repo, and I put it in the plugin folder. For some reason it didn't come with the zip.
4. I run composer install again, and it installs lots of stuff.  
5. Now I get an error that _global_media.site_id_ is deprecated, and it wants me to use _network-media-library/site_id_ instead. 

Whats going on? Do I need both plugins? There is nothing in your readme about Network Media Library.

**Comment by bueltge** [comment]
The network global media plugin is a fork from this plugin, not on my focus and not in place in test. If you will work with a global media library than use the MGM, not more. It is available via download on the release page or via Composer, if the knowledge of composer is existent.

**Comment by peter-mumford** [comment]
OK, I see that these plugins are not connected.
