### ISSUE TITLE
JS error on click global media 

### ISSUE THREAD

**Issue by peter-mumford** [bueltge/multisite-global-media#77]
I can't see the Global Media library. I get this JS error when I click the Global Media option.. see screenshot.  The files visible are specific to the sub-site.  They are NOT global media files.
 
![global-media-library](https://user-images.githubusercontent.com/31707793/52592614-db00d800-2e14-11e9-8108-d6c2ad9d0a93.png)

**Comment by widoz** [comment]
@peter-mumford Could you try to deactivate all plugins and check again if the problem persists?
Sounds like some conflict with a plugin

**Comment by peter-mumford** [comment]
@widoz you are correct. The conflict is with WP Real Media Library.

**Comment by bueltge** [comment]
@peter-mumford So we can close this issue? I do that, feel free to reopen again, if the topic is not solved in your context.
