### ISSUE TITLE
Path Issues and CDN Usage

### ISSUE THREAD

**Issue by Rothwild** [bueltge/multisite-global-media#78]
DEUTSCH: Die URL der Medienzentrale wird nicht bei der Bildanbindung auf einer anderen Seite verwendet, soweit ich das sehen kann. Ist das richtig? Zum besseren Verständnis: http://test.example.com soll die Bilder von http://media.example.com anzeigen. Hier funktioniert das Plugin auch super! Danke auch an dieser Stelle mal dafür! Das eingebundene Bild hat das einen Image-Pfad, der von "test.example.com" ausgeliefert wird. Soweit, so klar. Nun zur eigentlichen Frage: Gibt das nicht Durcheinander bei der Verwendung eines CDN? Wo wird dann das CDN eingesetzt? Auf media.example.com? Oder auf test.example.com? Oder spielt hier der Pfad gar keine Rolle?

ENGLISH: The URL of the media center is not used for the image link on another page, as far as I can see. Is that correct? For a better understanding: http://test.example.com should display the pictures from http://media.example.com. Here the plugin also works great! Thanks also at this point times for it! The integrated image has an image path, which is delivered by "test.example.com". So far, so clear. Now to the actual question: Isn't there confusion when using a CDN? Where is the CDN then used? On media.example.com? Or on test.example.com? Or doesn't the path play any role here?

**Comment by bueltge** [comment]
Die Dateien liegen immer in einer Site des netzwerkes, in deinem fall in `test.example.com`, da dies vermutlich die Site mit ID 1 ist. Es sei denn du hast die Site ID angepasst. Die globale Mediathek stellt kein CDN dar, es sein denn dass diese domain darauf gesetzt wurde, schneller, höher, weiter. CDN ist ja eine Auslagerung für das schnelle Ausliefern von Dateien. Die globale Mediathek ist eine Lösung, damit zentral Dateien bereit gestellt werden, bspw. für div. Autoren in verschiedenen Seiten, bspw. nach Rechtsprüfung o.ä. - die dann in jeder Site genutzt werden können. Im Thema SEO bspw. ist dies eher ein nachteil, da die Bilder eine andere URL haben als der Artikel, Content, daher kopiert bzgl. SEO lieber alle Bilder und hält sie in jeder Site vor.
