### ISSUE TITLE
Not seeing the Global media tab.

### ISSUE THREAD

**Issue by KrispyKrisKringle** [bueltge/multisite-global-media#79]
Hallo aus Kürten!  Naja, I went through four installations, including messing with the mu-loader.  I finally was able to get this to work without errors (loading and parse errors).  However I am not seeing the tabs.  I am running a child theme of 2010, on the latest Wordpress.  I created a multi-site out of an existing site, so it is not a clean installation.

KriebelRestauration.de

LG 
Jonathan

**Comment by bueltge** [comment]
Hallo.
have you activated the plugin for the hole network? Have you an site in your network with ID 1? That's the default site to store the media files for the hole network.
