### ISSUE TITLE
No working in Elementor media gallery...

### ISSUE THREAD

**Issue by itroww** [bueltge/multisite-global-media#84]
No working in Elementor media gallery...

**Comment by itroww** [comment]
Working only in the regular gallery (last link on the left)
Not working as extra tab in any case...

**Comment by bueltge** [comment]
Have you ask the dev or support team Elementor? We would not test any plugin or theme. We develop only on the standard of wp.

**Comment by lavalldesign** [comment]
Elementor support says:

"Unfortunately, we cannot provide support or control of third-party plugins.
Please try contacting the author of your plugin, for extra guidance. "

https://wordpress.org/support/topic/allow-elementor-to-work-with-multisite-global-media-plugin/

what can we do?

**Comment by bueltge** [comment]
But I mean is not a problem from a third-party plugin, because our plugin doesn't create any new media view, we only enhance the media screen from the core. Maybe Elementor creates a custom view, don't use a core media overlay. However, maybe I will check them in local install. Is the Elementor plugin an open, free plugin? I haven't any knowledge about this plugin.

**Comment by axraph** [comment]
@bueltge I had a similar problem with another front-end page builder plugin, beaver builder,  just like elementor, all we needed is to load the JS on front end using wp_footer hook and the snippet from https://github.com/bueltge/multisite-global-media/wiki/Add-theme-support-for-the-Customizer-Image-Control. Works perfectly. I hope that helps.

**Comment by marktenney** [comment]
I was able to patch this for Beaver Builder with the following code:

```<?php
// Add Global Media Gallery JS to Customize.php
function add_multisite_global_media_to_customizer() {
    wp_register_script(
        'multisite_global_media',
        '/wp-content/plugins/multisite-global-media/assets/js/global-media.js',
        ['jquery'],
        '1.1',
        true
    );
    wp_enqueue_script( 'multisite_global_media' );
}
add_action( 'customize_controls_print_footer_scripts', 'add_multisite_global_media_to_customizer' );
add_action( 'wp_enqueue_media', 'add_multisite_global_media_to_customizer' );```

The first action adds the plugin javascript to the customizer, while the second action adds it to Beaver Builder. I suspect that the second action might even do what's needed for the the customizer, too, but I haven't tried that yet.

**Comment by bueltge** [comment]
Thanks, @marktenney and @axraph, leave it now at the Wiki https://github.com/bueltge/multisite-global-media/wiki/Add-support-for-Beaver-Builder,-Elementor-Plugin
