### ISSUE TITLE
Not seeing Global Media Tab

### ISSUE THREAD

**Issue by gfors** [bueltge/multisite-global-media#9]
WP Version: 4.9.2

Steps to reproduce:

1. Installed plugin
2. Adjusted constant SITE_ID in "multisite-global-media.php" to 1 (the main site should be hosting the global media)
3. Network activated plugin
4. Added media to main site
5. No "Global media" tab is showing in any media modals/windows at all on other sites

**Comment by bueltge** [comment]
You should see the "Global Media" Tab in each Modal view, like on Posts --> Add Media, left side of the modal. I tested it shortly in WP 5.-alpha.

**Comment by gfors** [comment]
Which is precisely what the issue is, that its not showing up there :)

Not working in native content "add media", not working in media->add, not working in ACF images, not working for featured images.

**Comment by bueltge** [comment]
Have you tried to remove, deactivate all other plugin, use a default theme. Active the WP_DEBUG mode, so maybe you get the problem.

**Comment by thechrise** [comment]
@gfors, I was having the same issue. Turn out that the zip file doesn't include the assets folder. Try adding those files.

@bueltge - Now that I have the Global Media tab displaying, I can't get it to populate with images. I've tried enabling the 2017 theme and disabling all other plugins with no success. Can't get any errors to populate the WP logs either. Any thoughts?

**Comment by thechrise** [comment]
@bueltge - I just tried switching out v3 for v2 of the main php script and it seems to be functioning properly.

**Comment by bueltge** [comment]
Ok, thanks. So that we should check the differences for an error.

**Comment by bueltge** [comment]
The new version 0.0.4 should fix the problem https://github.com/bueltge/multisite-global-media/releases/tag/0.0.4
Is tested also in the current alpha of WP 5.0
