### ISSUE TITLE
Global Media Selection layer keep loading

### ISSUE THREAD

**Issue by kevinchu-work** [bueltge/multisite-global-media#96]
The Global media selection function keep loading when user is not "Super Admin". As long as the user/write are not "Super Admin", the loading spinner won't go away and no image can be shows.

I believe that the user needs to be network_admin in order to normally operate 

I like the plugins because it is exactly what we want to be. Keep it up~~~

<img width="472" alt="Edit_Post_‹_Kwun_Tong__A__—_WordPress" src="https://user-images.githubusercontent.com/29423338/65743543-a897b700-e127-11e9-8f9c-dce1246ae4d7.png">

**Comment by bueltge** [comment]
Is that in each side a problem or only on the side, there store the media, that is defined via the plugin?

**Comment by kevinchu-work** [comment]
Sorry, my mistake

Just did some testing between sites & users and turned out this seems to be **a user permission issue**, not a bug. Below is what my learnt:

**Case 1:**
Site A (ID: 1) - the media library, with super admin
Site B - user B (admin of Site B)
Site C - user C (admin of Site C)

In case 1, user B & C can't access to media from Site A and the forever loading case happened. super admin able to access media everywhere without issue.

**Case 2:**
Site A (ID: 1) - the media library, with super admin
Site B - user B (admin of Site B, plus Contributor access of Site A)
Site C - user C (admin of Site C, plus Contributor access of Site A)

In case 2, both user B & C access to Site A media library without any problem. As long as the user role >= Contributor, it works fine

**Comment by bueltge** [comment]
Thanks for clarifying.
